# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createServerForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(570, 276)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("*{\n"
"    font-family: century gothic;\n"
"    font-size: 20px;\n"
"}\n"
"#exitButton{\n"
"    /*background-color: red;*/\n"
"    border-radius: 15px;\n"
"    background-size: 5px;\n"
"}\n"
"QScrollArea{\n"
"    background-color: #333;\n"
"}\n"
"QMainWindow{\n"
"    background-color: transparent;\n"
"}\n"
"#passwordText{\n"
"    type: password;\n"
"}\n"
"QFrame{\n"
"    background: #333;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton{\n"
"    border-radius: 15px;\n"
"    background: rgb(0, 170, 127);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover{\n"
"    background: #333;\n"
"    color: rgb(0, 170, 127);\n"
"}\n"
"#logOffButton{\n"
"    background: rgb(255, 98, 51);\n"
"}\n"
"#logOffButton:hover{\n"
"    background: #333;\n"
"    color: rgb(255, 98, 51);\n"
"}\n"
"QInputDialog{\n"
"    width: 50px;\n"
"    height: 50px;\n"
"}\n"
"#toolButton{\n"
"    border-radius: 60px;\n"
"    background: red;\n"
"}\n"
"QLabel{\n"
"    color: white;\n"
"}\n"
"QLineEdit{\n"
"    padding-bottom: 5px;\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #717072;\n"
"    border-bottom: 1px solid #717072;\n"
"}\n"
"QInputDialog QLabel{\n"
"    background: transparent;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"}\n"
"QInputDialog QPushButton{\n"
"    background: transparent;\n"
"    color: black;\n"
"}\n"
"QInputDialog QPushButton:hover{\n"
"    background: transparent;\n"
"    color: red;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 20, 541, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.serverName = QtWidgets.QLabel(self.frame)
        self.serverName.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.serverName.setStyleSheet("font-size: 28px;")
        self.serverName.setAlignment(QtCore.Qt.AlignCenter)
        self.serverName.setObjectName("serverName")
        self.exitButton = QtWidgets.QToolButton(self.frame)
        self.exitButton.setGeometry(QtCore.QRect(480, 10, 41, 31))
        self.exitButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon)
        self.exitButton.setShortcut("")
        self.exitButton.setAutoRepeatDelay(300)
        self.exitButton.setObjectName("exitButton")
        self.showUsersButton = QtWidgets.QToolButton(self.frame)
        self.showUsersButton.setGeometry(QtCore.QRect(430, 10, 41, 31))
        self.showUsersButton.setStyleSheet("background-color: transparent")
        self.showUsersButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showUsersButton.setIcon(icon1)
        self.showUsersButton.setShortcut("")
        self.showUsersButton.setAutoRepeatDelay(300)
        self.showUsersButton.setObjectName("showUsersButton")
        self.serverNameInput = QtWidgets.QLineEdit(self.frame)
        self.serverNameInput.setGeometry(QtCore.QRect(310, 50, 211, 31))
        self.serverNameInput.setInputMask("")
        self.serverNameInput.setObjectName("serverNameInput")
        self.createServerButton = QtWidgets.QPushButton(self.frame)
        self.createServerButton.setGeometry(QtCore.QRect(330, 130, 191, 51))
        self.createServerButton.setObjectName("createServerButton")
        self.hasPasswordCheckBox = QtWidgets.QCheckBox(self.frame)
        self.hasPasswordCheckBox.setGeometry(QtCore.QRect(40, 90, 181, 31))
        self.hasPasswordCheckBox.setStyleSheet("color: white; font-size:28px")
        self.hasPasswordCheckBox.setObjectName("hasPasswordCheckBox")
        self.passwordInput = QtWidgets.QLineEdit(self.frame)
        self.passwordInput.setGeometry(QtCore.QRect(30, 140, 281, 31))
        self.passwordInput.setInputMask("")
        self.passwordInput.setObjectName("passwordInput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.serverName.setText(_translate("MainWindow", "Название сервера:"))
        self.serverNameInput.setPlaceholderText(_translate("MainWindow", "Введите название"))
        self.createServerButton.setText(_translate("MainWindow", "Создать сервер"))
        self.hasPasswordCheckBox.setText(_translate("MainWindow", "Пароль"))
        self.passwordInput.setPlaceholderText(_translate("MainWindow", "Введите пароль"))
