# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lobby.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 492)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("*{\n"
"    font-family: century gothic;\n"
"    font-size: 20px;\n"
"}\n"
"#exitButton{\n"
"    /*background-color: red;*/\n"
"    border-radius: 15px;\n"
"    background-size: 5px;\n"
"}\n"
"QMainWindow{\n"
"    background-color: transparent;\n"
"}\n"
"#passwordText{\n"
"    type: password;\n"
"}\n"
"QFrame{\n"
"    background: #333;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton{\n"
"    border-radius: 15px;\n"
"    background: red;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover{\n"
"    background: #333;\n"
"    color: red;\n"
"}\n"
"QInputDialog{\n"
"    width: 50px;\n"
"    height: 50px;\n"
"}\n"
"#toolButton{\n"
"    border-radius: 60px;\n"
"    background: red;\n"
"}\n"
"QLabel{\n"
"    color: white;\n"
"}\n"
"QLineEdit{\n"
"    padding-bottom: 5px;\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #717072;\n"
"    border-bottom: 1px solid #717072;\n"
"}\n"
"QInputDialog QLabel{\n"
"    background: transparent;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"}\n"
"QInputDialog QPushButton{\n"
"    background: transparent;\n"
"    color: black;\n"
"}\n"
"QInputDialog QPushButton:hover{\n"
"    background: transparent;\n"
"    color: red;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 20, 531, 291))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 0, 281, 51))
        self.label.setStyleSheet("font-size: 28px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(20, 50, 261, 201))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 261, 201))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.updateButton = QtWidgets.QPushButton(self.frame)
        self.updateButton.setGeometry(QtCore.QRect(310, 50, 181, 41))
        self.updateButton.setObjectName("updateButton")
        self.logOffButton = QtWidgets.QPushButton(self.frame)
        self.logOffButton.setGeometry(QtCore.QRect(310, 150, 181, 41))
        self.logOffButton.setObjectName("logOffButton")
        self.exitButton = QtWidgets.QToolButton(self.frame)
        self.exitButton.setGeometry(QtCore.QRect(470, 10, 41, 31))
        self.exitButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon)
        self.exitButton.setShortcut("")
        self.exitButton.setAutoRepeatDelay(300)
        self.exitButton.setObjectName("exitButton")
        self.createServerButton = QtWidgets.QPushButton(self.frame)
        self.createServerButton.setGeometry(QtCore.QRect(310, 100, 181, 41))
        self.createServerButton.setObjectName("createServerButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 756, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Список серверов"))
        self.updateButton.setText(_translate("MainWindow", "Обновить"))
        self.logOffButton.setText(_translate("MainWindow", "Выйти с аккаунта"))
        self.createServerButton.setText(_translate("MainWindow", "Создать сервер"))
