# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Secondary.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(969, 669)
        MainWindow.setStyleSheet("*{\n"
"    font-family: century gothic;\n"
"    font-size: 20px;\n"
"}\n"
"QMainWindow{\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton{\n"
"    border-radius: 15px;\n"
"    background: rgb(0, 170, 127);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover{\n"
"    background: #333;\n"
"    color: rgb(0, 170, 127);\n"
"}\n"
"#whisperButton{\n"
"    color: white;\n"
"}\n"
"#exitAccountButton, #disconnectButton{\n"
"    background: rgb(255, 98, 51);\n"
"}\n"
"#exitAccountButton:hover, #disconnectButton:hover{\n"
"    background: #333;\n"
"    color: rgb(255, 98, 51);\n"
"}\n"
"#textBrowser{\n"
"    font-size: 16px;\n"
"}\n"
"#toolButton{\n"
"    border-radius: 60px;\n"
"    background: red;\n"
"}\n"
"QLabel{\n"
"    color: white;\n"
"}\n"
"QFrame{\n"
"    background: #333;\n"
"    border-radius: 15px;\n"
"}\n"
"QLineEdit{\n"
"    padding-bottom: 5px;\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #717072;\n"
"    border-bottom: 1px solid #717072;\n"
"}\n"
"#sendButton{\n"
"    border-radius: 15px;\n"
"    background: lightgrey;\n"
"}\n"
"#sendButton:hover{\n"
"    background: #333;\n"
"}\n"
"#exitButton{\n"
"    /*background-color: red;*/\n"
"    border-radius: 15px;\n"
"    background-size: 5px;\n"
"}\n"
"#showUsersButton{\n"
"    border-radius: 15px;\n"
"    background-size: 5px;\n"
"}\n"
"#searchButton{\n"
"    border-radius: 15px;\n"
"    background-size: 5px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 941, 591))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(20, 70, 901, 371))
        self.textBrowser.setStyleSheet("background-color: lightgrey;")
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(20, 460, 611, 111))
        self.textEdit.setStyleSheet("background-color: lightgrey;")
        self.textEdit.setObjectName("textEdit")
        self.serverNameLabel = QtWidgets.QLabel(self.frame)
        self.serverNameLabel.setGeometry(QtCore.QRect(30, 10, 401, 51))
        self.serverNameLabel.setText("")
        self.serverNameLabel.setWordWrap(True)
        self.serverNameLabel.setObjectName("serverNameLabel")
        self.searchButton = QtWidgets.QPushButton(self.frame)
        self.searchButton.setGeometry(QtCore.QRect(660, 10, 201, 51))
        self.searchButton.setObjectName("searchButton")
        self.abortSearchButton = QtWidgets.QPushButton(self.frame)
        self.abortSearchButton.setGeometry(QtCore.QRect(450, 10, 201, 51))
        self.abortSearchButton.setObjectName("abortSearchButton")
        self.uploadButton = QtWidgets.QPushButton(self.frame)
        self.uploadButton.setGeometry(QtCore.QRect(730, 520, 191, 51))
        self.uploadButton.setObjectName("uploadButton")
        self.downloadButton = QtWidgets.QPushButton(self.frame)
        self.downloadButton.setGeometry(QtCore.QRect(730, 460, 191, 51))
        self.downloadButton.setObjectName("downloadButton")
        self.showUsersButton = QtWidgets.QToolButton(self.frame)
        self.showUsersButton.setGeometry(QtCore.QRect(1080, 10, 41, 31))
        self.showUsersButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showUsersButton.setIcon(icon)
        self.showUsersButton.setShortcut("")
        self.showUsersButton.setAutoRepeatDelay(300)
        self.showUsersButton.setObjectName("showUsersButton")
        self.messagesAmount = QtWidgets.QLabel(self.frame)
        self.messagesAmount.setGeometry(QtCore.QRect(720, 19, 81, 31))
        self.messagesAmount.setText("")
        self.messagesAmount.setAlignment(QtCore.Qt.AlignCenter)
        self.messagesAmount.setObjectName("messagesAmount")
        self.backButton = QtWidgets.QToolButton(self.frame)
        self.backButton.setGeometry(QtCore.QRect(660, 10, 51, 51))
        self.backButton.setStyleSheet("background-color: transparent")
        self.backButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon1)
        self.backButton.setIconSize(QtCore.QSize(80, 80))
        self.backButton.setObjectName("backButton")
        self.forwardButton = QtWidgets.QToolButton(self.frame)
        self.forwardButton.setGeometry(QtCore.QRect(810, 10, 51, 51))
        self.forwardButton.setStyleSheet("background-color: transparent")
        self.forwardButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forwardButton.setIcon(icon2)
        self.forwardButton.setIconSize(QtCore.QSize(80, 80))
        self.forwardButton.setObjectName("forwardButton")
        self.sendButton = QtWidgets.QToolButton(self.frame)
        self.sendButton.setGeometry(QtCore.QRect(640, 460, 81, 111))
        self.sendButton.setStyleSheet("")
        self.sendButton.setText("")
        self.sendButton.setObjectName("sendButton")
        self.exitButton = QtWidgets.QToolButton(self.frame)
        self.exitButton.setGeometry(QtCore.QRect(880, 10, 51, 41))
        self.exitButton.setStyleSheet("background: transparent")
        self.exitButton.setText("")
        self.exitButton.setObjectName("exitButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 969, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MyMessenger"))
        self.searchButton.setText(_translate("MainWindow", "Поиск"))
        self.abortSearchButton.setText(_translate("MainWindow", "Сбросить поиск"))
        self.uploadButton.setText(_translate("MainWindow", "Загрузить файлы"))
        self.downloadButton.setText(_translate("MainWindow", "Скачать файлы"))
